# Generated by Django 3.1.3 on 2021-04-20 21:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20210413_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
